'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("fInfo.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property Carbon_copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Carbon_copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Close_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Close_button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Close_button_mouse_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Close_button_mouse_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Close_button_mouse_over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Close_button_mouse_over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property diagListbox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("diagListbox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Dialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fTray() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("fTray", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property fTray_EOC() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("fTray_EOC", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property fTray_Log() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("fTray_Log", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property fTray_Start() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("fTray_Start", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property fTray_stop() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("fTray_stop", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property fTray_Warning() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("fTray_Warning", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Help_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Help_button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Help_button_mouse_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Help_button_mouse_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Help_button_mouse_over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Help_button_mouse_over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Min_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Min_button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Min_button_mouse_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Min_button_mouse_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Min_button_mouse_over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Min_button_mouse_over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pCarbon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pCarbon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Red() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Red", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Settings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Settings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TL_GREEN() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("TL_GREEN", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property TL_RED() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("TL_RED", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property TL_YELLOW() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("TL_YELLOW", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property UI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Yellow() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Yellow", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
